// Auto-generated by script
export const MUSIC = [
  {
    "id": 1,
    "title": "십센치 선재 업고 튀어 OST 봄 눈 Spring Snow",
    "artist": "10cm",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/100/400/400",
    "audioUrl": "/media/music/10cm - 십센치 선재 업고 튀어 OST 봄 눈 Spring Snow.mp3",
    "lrcUrl": null
  },
  {
    "id": 2,
    "title": "Dionysus",
    "artist": "BTS (방탄소년단)",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/101/400/400",
    "audioUrl": "/media/music/BTS (방탄소년단) - Dionysus.mp3",
    "lrcUrl": null
  },
  {
    "id": 3,
    "title": "Spring Day",
    "artist": "BTS (방탄소년단)",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/102/400/400",
    "audioUrl": "/media/music/BTS (방탄소년단) - Spring Day.mp3",
    "lrcUrl": null
  },
  {
    "id": 4,
    "title": "Airplane pt.2",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/103/400/400",
    "audioUrl": "/media/music/BTS - Airplane pt.2.mp3",
    "lrcUrl": "/media/music/lrc_files/BTS - Airplane pt.2.lrc"
  },
  {
    "id": 5,
    "title": "Black Swan",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/104/400/400",
    "audioUrl": "/media/music/BTS - Black Swan.mp3",
    "lrcUrl": "/media/music/lrc_files/BTS - Black Swan.lrc"
  },
  {
    "id": 6,
    "title": "Butter",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/105/400/400",
    "audioUrl": "/media/music/BTS - Butter.mp3",
    "lrcUrl": "/media/music/lrc_files/BTS - Butter.lrc"
  },
  {
    "id": 7,
    "title": "Butterfly",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/106/400/400",
    "audioUrl": "/media/music/BTS - Butterfly.mp3",
    "lrcUrl": "/media/music/lrc_files/BTS - Butterfly.lrc"
  },
  {
    "id": 8,
    "title": "DNA",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/107/400/400",
    "audioUrl": "/media/music/BTS - DNA.mp3",
    "lrcUrl": "/media/music/lrc_files/BTS - DNA.lrc"
  },
  {
    "id": 9,
    "title": "Dynamite (Original)",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/108/400/400",
    "audioUrl": "/media/music/BTS - Dynamite (Original).mp3",
    "lrcUrl": null
  },
  {
    "id": 10,
    "title": "Euphoria",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/109/400/400",
    "audioUrl": "/media/music/BTS - Euphoria.mp3",
    "lrcUrl": "/media/music/lrc_files/BTS - Euphoria.lrc"
  },
  {
    "id": 11,
    "title": "Filter",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/110/400/400",
    "audioUrl": "/media/music/BTS - Filter.mp3",
    "lrcUrl": "/media/music/lrc_files/BTS - Filter.lrc"
  },
  {
    "id": 12,
    "title": "Friends",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/111/400/400",
    "audioUrl": "/media/music/BTS - Friends.mp3",
    "lrcUrl": "/media/music/lrc_files/BTS - Friends.lrc"
  },
  {
    "id": 13,
    "title": "IDOL",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/112/400/400",
    "audioUrl": "/media/music/BTS - IDOL.mp3",
    "lrcUrl": "/media/music/lrc_files/BTS - IDOL.lrc"
  },
  {
    "id": 14,
    "title": "Inner Child",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/113/400/400",
    "audioUrl": "/media/music/BTS - Inner Child.mp3",
    "lrcUrl": "/media/music/lrc_files/BTS - Inner Child.lrc"
  },
  {
    "id": 15,
    "title": "Jamais Vu",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/114/400/400",
    "audioUrl": "/media/music/BTS - Jamais Vu.mp3",
    "lrcUrl": "/media/music/lrc_files/BTS - Jamais Vu.lrc"
  },
  {
    "id": 16,
    "title": "ON",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/115/400/400",
    "audioUrl": "/media/music/BTS - ON.mp3",
    "lrcUrl": null
  },
  {
    "id": 17,
    "title": "RM - Always",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/116/400/400",
    "audioUrl": "/media/music/BTS - RM - Always.mp3",
    "lrcUrl": null
  },
  {
    "id": 18,
    "title": "Tear",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/117/400/400",
    "audioUrl": "/media/music/BTS - Tear.mp3",
    "lrcUrl": null
  },
  {
    "id": 19,
    "title": "소우주 (Mikrokosmos)",
    "artist": "BTS",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/118/400/400",
    "audioUrl": "/media/music/BTS - 소우주 (Mikrokosmos).mp3",
    "lrcUrl": null
  },
  {
    "id": 20,
    "title": "지금 만나러 갑니다",
    "artist": "Deok Hwan (덕환)",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/119/400/400",
    "audioUrl": "/media/music/Deok Hwan (덕환) - 지금 만나러 갑니다.mp3",
    "lrcUrl": null
  },
  {
    "id": 21,
    "title": "Love wins all",
    "artist": "IU",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/120/400/400",
    "audioUrl": "/media/music/IU - Love wins all.mp3",
    "lrcUrl": "/media/music/lrc_files/IU - Love wins all.lrc"
  },
  {
    "id": 22,
    "title": "MORE",
    "artist": "j-hope",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/121/400/400",
    "audioUrl": "/media/music/j-hope - MORE.mp3",
    "lrcUrl": null
  },
  {
    "id": 23,
    "title": "Monologue",
    "artist": "Jae Yeon",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/122/400/400",
    "audioUrl": "/media/music/Jae Yeon - Monologue.mp3",
    "lrcUrl": null
  },
  {
    "id": 24,
    "title": "A Day",
    "artist": "Jong Ho (ATEEZ)",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/123/400/400",
    "audioUrl": "/media/music/Jong Ho (ATEEZ) - A Day.mp3",
    "lrcUrl": null
  },
  {
    "id": 25,
    "title": "Standing Next to You",
    "artist": "Jung Kook",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/124/400/400",
    "audioUrl": "/media/music/Jung Kook - Standing Next to You.mp3",
    "lrcUrl": "/media/music/lrc_files/Jung Kook - Standing Next to You.lrc"
  },
  {
    "id": 26,
    "title": "See The Light",
    "artist": "Lim Hyunsik (BTOB)",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/125/400/400",
    "audioUrl": "/media/music/Lim Hyunsik (BTOB) - See The Light.mp3",
    "lrcUrl": null
  },
  {
    "id": 27,
    "title": "유서 (강릉에서)",
    "artist": "MC SNIPER",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/126/400/400",
    "audioUrl": "/media/music/MC SNIPER - 유서 (강릉에서).mp3",
    "lrcUrl": null
  },
  {
    "id": 28,
    "title": "Like A Dream",
    "artist": "MINNIE",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/127/400/400",
    "audioUrl": "/media/music/MINNIE - Like A Dream.mp3",
    "lrcUrl": null
  },
  {
    "id": 29,
    "title": "Run",
    "artist": "Nell",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/128/400/400",
    "audioUrl": "/media/music/Nell - Run.mp3",
    "lrcUrl": null
  },
  {
    "id": 30,
    "title": "JEONG SEWOON (정세운) - Fall in Love",
    "artist": "OST King the Land",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/129/400/400",
    "audioUrl": "/media/music/OST King the Land - JEONG SEWOON (정세운) - Fall in Love.mp3",
    "lrcUrl": null
  },
  {
    "id": 31,
    "title": "Jung Seung Hwan (정승환) - Get To You (너에게 닿을게)",
    "artist": "OST King the Land",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/130/400/400",
    "audioUrl": "/media/music/OST King the Land - Jung Seung Hwan (정승환) - Get To You (너에게 닿을게).mp3",
    "lrcUrl": null
  },
  {
    "id": 32,
    "title": "Lim Kim (림킴) - Confess To You",
    "artist": "OST King the Land",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/131/400/400",
    "audioUrl": "/media/music/OST King the Land - Lim Kim (림킴) - Confess To You.mp3",
    "lrcUrl": null
  },
  {
    "id": 33,
    "title": "Punch (펀치) - Keep Me Busy",
    "artist": "OST King the Land",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/132/400/400",
    "audioUrl": "/media/music/OST King the Land - Punch (펀치) - Keep Me Busy.mp3",
    "lrcUrl": null
  },
  {
    "id": 34,
    "title": "Davichi - Please Don't Cry",
    "artist": "OST The King_ The Eternal Monarch",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/133/400/400",
    "audioUrl": "/media/music/OST The King_ The Eternal Monarch - Davichi - Please Don't Cry.mp3",
    "lrcUrl": null
  },
  {
    "id": 35,
    "title": "Hwa Sa - Orbit",
    "artist": "OST The King_ The Eternal Monarch",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/134/400/400",
    "audioUrl": "/media/music/OST The King_ The Eternal Monarch - Hwa Sa - Orbit.mp3",
    "lrcUrl": null
  },
  {
    "id": 36,
    "title": "Kim Jong Wan (NELL) - Gravity (연)",
    "artist": "OST The King_ The Eternal Monarch",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/135/400/400",
    "audioUrl": "/media/music/OST The King_ The Eternal Monarch - Kim Jong Wan (NELL) - Gravity (연).mp3",
    "lrcUrl": null
  },
  {
    "id": 37,
    "title": "Paul Kim - Dream",
    "artist": "OST The King_ The Eternal Monarch",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/136/400/400",
    "audioUrl": "/media/music/OST The King_ The Eternal Monarch - Paul Kim - Dream.mp3",
    "lrcUrl": null
  },
  {
    "id": 38,
    "title": "YONGZOO - Maze",
    "artist": "OST The King_ The Eternal Monarch",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/137/400/400",
    "audioUrl": "/media/music/OST The King_ The Eternal Monarch - YONGZOO - Maze.mp3",
    "lrcUrl": null
  },
  {
    "id": 39,
    "title": "My Tale (Psycho But It's Okay OST Part.3) Псих, но всё в порядке 3",
    "artist": "Park Won (박원)",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/138/400/400",
    "audioUrl": "/media/music/Park Won (박원) - My Tale (Psycho But It's Okay OST Part.3) Псих, но всё в порядке 3.mp3",
    "lrcUrl": null
  },
  {
    "id": 40,
    "title": "Come back to me",
    "artist": "RM (BTS)",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/139/400/400",
    "audioUrl": "/media/music/RM (BTS) - Come back to me.mp3",
    "lrcUrl": null
  },
  {
    "id": 41,
    "title": "Lonely",
    "artist": "RM (BTS)",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/140/400/400",
    "audioUrl": "/media/music/RM (BTS) - Lonely.mp3",
    "lrcUrl": null
  },
  {
    "id": 42,
    "title": "Wild Flower (With Youjeen)",
    "artist": "RM",
    "year": 2024,
    "tags": [
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/141/400/400",
    "audioUrl": "/media/music/RM - Wild Flower (With Youjeen).mp3",
    "lrcUrl": null
  },
  {
    "id": 43,
    "title": "The Image of You (Remains in My Memory) [ OST Приморская деревня ЧаЧаЧа ]",
    "artist": "SANDEUL",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/142/400/400",
    "audioUrl": "/media/music/SANDEUL - The Image of You (Remains in My Memory) [ OST Приморская деревня ЧаЧаЧа ].mp3",
    "lrcUrl": null
  },
  {
    "id": 44,
    "title": "Here Always (승민 of Stray Kids) [ OST Приморская деревня ЧаЧаЧа ]",
    "artist": "Stray Kids (스트레이 키즈)",
    "year": 2024,
    "tags": [
      "OST",
      "K-Pop"
    ],
    "image": "https://picsum.photos/seed/143/400/400",
    "audioUrl": "/media/music/Stray Kids (스트레이 키즈) - Here Always (승민 of Stray Kids) [ OST Приморская деревня ЧаЧаЧа ].mp3",
    "lrcUrl": null
  },
  {
    "id": 45,
    "title": "Hear Me Out [OST Набранный вами номер]",
    "artist": "SURAN (수란)",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/144/400/400",
    "audioUrl": "/media/music/SURAN (수란) - Hear Me Out [OST Набранный вами номер].mp3",
    "lrcUrl": null
  },
  {
    "id": 46,
    "title": "I Am In Love",
    "artist": "VRomance feat. O Broject",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/145/400/400",
    "audioUrl": "/media/music/VRomance feat. O Broject - I Am In Love.mp3",
    "lrcUrl": null
  },
  {
    "id": 47,
    "title": "TRUE (OST из дорамы Мой Демон)",
    "artist": "YOARI",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/146/400/400",
    "audioUrl": "/media/music/YOARI - TRUE (OST из дорамы Мой Демон).mp3",
    "lrcUrl": null
  },
  {
    "id": 48,
    "title": "Lim Yeon - Numb",
    "artist": "[Номер, который вы набрали OST Part.2]",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/147/400/400",
    "audioUrl": "/media/music/[Номер, который вы набрали OST Part.2] - Lim Yeon - Numb.mp3",
    "lrcUrl": null
  },
  {
    "id": 49,
    "title": "Lee Suhyun (AKMU) - In Your Time",
    "artist": "[Я псих, но все нормально OST Part.4]",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/148/400/400",
    "audioUrl": "/media/music/[Я псих, но все нормально OST Part.4] - Lee Suhyun (AKMU) - In Your Time.mp3",
    "lrcUrl": null
  },
  {
    "id": 50,
    "title": "CHEEZE - Little by little",
    "artist": "[Я псих, но это нормально OST Part.6]",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/149/400/400",
    "audioUrl": "/media/music/[Я псих, но это нормально OST Part.6] - CHEEZE - Little by little.mp3",
    "lrcUrl": null
  },
  {
    "id": 51,
    "title": "(OST Part.4) Somewhere in This Universe. Где-то в этой вселенной (Каждый вдох становится чудом)",
    "artist": "_Спроси у звезд_ ⭐ SEUNG KWAN (승관)",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/150/400/400",
    "audioUrl": "/media/music/_Спроси у звезд_ ⭐ SEUNG KWAN (승관) - (OST Part.4) Somewhere in This Universe. Где-то в этой вселенной (Каждый вдох становится чудом).mp3",
    "lrcUrl": null
  },
  {
    "id": 52,
    "title": "나도 모르는 노래 (Hallelujah) [ OST Псих, но все в порядке ]",
    "artist": "김필 (Kim Feel)",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/151/400/400",
    "audioUrl": "/media/music/김필 (Kim Feel) - 나도 모르는 노래 (Hallelujah) [ OST Псих, но все в порядке ].mp3",
    "lrcUrl": null
  },
  {
    "id": 53,
    "title": "I Like You [Touch Your Heart OST 2019]",
    "artist": "김호중",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/152/400/400",
    "audioUrl": "/media/music/김호중 - I Like You [Touch Your Heart OST 2019].mp3",
    "lrcUrl": null
  },
  {
    "id": 54,
    "title": "피노키오 (1)",
    "artist": "로이킴",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/153/400/400",
    "audioUrl": "/media/music/로이킴 - 피노키오 (1).mp3",
    "lrcUrl": null
  },
  {
    "id": 55,
    "title": "피노키오",
    "artist": "로이킴",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/154/400/400",
    "audioUrl": "/media/music/로이킴 - 피노키오.mp3",
    "lrcUrl": null
  },
  {
    "id": 56,
    "title": "Breath OST 2 Псих, но всё впорядку",
    "artist": "샘김 Sam Kim",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/155/400/400",
    "audioUrl": "/media/music/샘김 Sam Kim - Breath OST 2 Псих, но всё впорядку.mp3",
    "lrcUrl": null
  },
  {
    "id": 57,
    "title": "꿈이로다",
    "artist": "송소희",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/156/400/400",
    "audioUrl": "/media/music/송소희 - 꿈이로다.mp3",
    "lrcUrl": null
  },
  {
    "id": 58,
    "title": "What If Love [Touch Your Heart OST Part.3]",
    "artist": "웬디 (WENDY)",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/157/400/400",
    "audioUrl": "/media/music/웬디 (WENDY) - What If Love [Touch Your Heart OST Part.3].mp3",
    "lrcUrl": null
  },
  {
    "id": 59,
    "title": "기도",
    "artist": "이예준",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/158/400/400",
    "audioUrl": "/media/music/이예준 - 기도.mp3",
    "lrcUrl": null
  },
  {
    "id": 60,
    "title": "In Silence",
    "artist": "자넷서 (Janet Suhh)",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/159/400/400",
    "audioUrl": "/media/music/자넷서 (Janet Suhh) - In Silence.mp3",
    "lrcUrl": null
  },
  {
    "id": 61,
    "title": "Good night [Touch Your Heart OST Part.5]",
    "artist": "정세운 (Jeong Sewoon)",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/160/400/400",
    "audioUrl": "/media/music/정세운 (Jeong Sewoon) - Good night [Touch Your Heart OST Part.5].mp3",
    "lrcUrl": null
  },
  {
    "id": 62,
    "title": "그대란 정원",
    "artist": "정은지 (Jeong Eun Ji)",
    "year": 2024,
    "tags": [
      "Music"
    ],
    "image": "https://picsum.photos/seed/161/400/400",
    "audioUrl": "/media/music/정은지 (Jeong Eun Ji) - 그대란 정원.mp3",
    "lrcUrl": null
  },
  {
    "id": 63,
    "title": "바람 [ OST Приморская деревня ЧаЧаЧа ]",
    "artist": "최유리 (Choi Yu Ree)",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/162/400/400",
    "audioUrl": "/media/music/최유리 (Choi Yu Ree) - 바람 [ OST Приморская деревня ЧаЧаЧа ].mp3",
    "lrcUrl": null
  },
  {
    "id": 64,
    "title": "선물 [OST Хватай Сон Джэ и беги]",
    "artist": "하성운",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/163/400/400",
    "audioUrl": "/media/music/하성운 - 선물 [OST Хватай Сон Джэ и беги].mp3",
    "lrcUrl": null
  },
  {
    "id": 65,
    "title": "You're Cold (더 많이 사랑한 쪽이 아프대) 1 Ost Псих, но всё в порядке",
    "artist": "헤이즈 (Heize)",
    "year": 2024,
    "tags": [
      "OST"
    ],
    "image": "https://picsum.photos/seed/164/400/400",
    "audioUrl": "/media/music/헤이즈 (Heize) - You're Cold (더 많이 사랑한 쪽이 아프대) 1 Ost Псих, но всё в порядке.mp3",
    "lrcUrl": null
  }
];
