import os
import json

MUSIC_DIR = r"e:\my_projects\korean_app\media\music"
LRC_DIR = os.path.join(MUSIC_DIR, "lrc_files")
OUTPUT_FILE = r"e:\my_projects\korean_app\src\data\music.ts"

def generate_music_data():
    music_files = [f for f in os.listdir(MUSIC_DIR) if f.endswith('.mp3')]
    lrc_files = set([f for f in os.listdir(LRC_DIR) if f.endswith('.lrc')]) if os.path.exists(LRC_DIR) else set()
    
    music_data = []
    
    for idx, f in enumerate(music_files):
        # f is something like: "BTS - Dynamite (Original).mp3"
        # we will extract artist and title by splitting " - "
        filename_no_ext = os.path.splitext(f)[0]
        
        parts = filename_no_ext.split(' - ', 1)
        if len(parts) == 2:
            artist = parts[0].strip()
            title = parts[1].strip()
        else:
            artist = "Unknown Artist"
            title = filename_no_ext

        # Tags inference
        tags = []
        if 'OST' in filename_no_ext.upper():
            tags.append('OST')
        
        lower_artist = artist.lower()
        if any(kpop_artist in lower_artist for kpop_artist in ['bts', 'stray kids', 'ive', 'newjeans', 'iu', 'ateez', 'rm', 'j-hope', 'jung kook']):
            tags.append('K-Pop')
        
        if not tags:
            tags.append('Music')

        lrc_filename = f"{filename_no_ext}.lrc"
        has_lrc = lrc_filename in lrc_files
        
        song = {
            "id": idx + 1,
            "title": title,
            "artist": artist,
            "year": 2024, # placeholder
            "tags": tags,
            "image": f"https://picsum.photos/seed/{idx+100}/400/400",
            "audioUrl": f"/media/music/{f}",
            "lrcUrl": f"/media/music/lrc_files/{lrc_filename}" if has_lrc else None
        }
        
        music_data.append(song)
        
    # Write to TS file
    ts_content = f"// Auto-generated by script\nexport const MUSIC = {json.dumps(music_data, indent=2, ensure_ascii=False)};\n"
    
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(ts_content)
        
    print(f"Successfully generated {len(music_data)} songs in {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_music_data()
